package myteam.testproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class datadata2 implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   public datadata2()
   {
   }

}