package myteam.testproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Person implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PERSON_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "PERSON_ID_SEQ", name = "PERSON_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label(value = "name")
   private java.lang.String name;

   @org.kie.api.definition.type.Label(value = "surname")
   private java.lang.String surname;

   public Person()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getSurname()
   {
      return this.surname;
   }

   public void setSurname(java.lang.String surname)
   {
      this.surname = surname;
   }

   public Person(java.lang.Long id, java.lang.String name,
         java.lang.String surname)
   {
      this.id = id;
      this.name = name;
      this.surname = surname;
   }

}